export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_ALL_TODOS = 'REMOVE_ALL_TODOS';
export const LANDING_SEARCH_RESULTS = 'LANDING_SEARCH_RESULTS';
export const PAGE_LOAD = 'PAGE_LOAD';